name: Manually Run Git Action

on:
  workflow_dispatch:

jobs:
  Manually Run Git Action:
    runs-on: ubuntu-latest
    
    steps:
     - name: Create Git Action
       uses: actions/checkout@v2
     - name: Print Hello World
       run: |
         cat hello.txt

  